### ISSUE TITLE
onelogin terraform-import panic: runtime error

### ISSUE THREAD

**Issue by ghost** [onelogin/onelogin#5]
Hi,

When trying to run `onelogin terraform-import onelogin_apps`
The following error happens:

```
Terraform Import!
Collecting Apps from OneLogin...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x143fef6]goroutine 1 [running]:
github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp.(*OLHTTPService).executeHTTP(0xc000108c28, 0xc0000be900, 0xc00002e540, 0x28, 0x1546ef5, 0x5, 0xc000021e00, 0x14d55e0, 0xc00006f6b0, 0x0, ...)
	/Users/amansour/go/src/github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp/olrequest.go:203 +0xf6
github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp.OLHTTPService.Create(0x154a66c, 0xf, 0xc000034013, 0x40, 0xc000034077, 0x40, 0xc00002e132, 0x13, 0x15f57c0, 0xc000021ad0, ...)
	/Users/amansour/go/src/github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp/olrequest.go:103 +0x3ec
github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp.(*OLHTTPService).mintBearerToken(0xc0001092c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14fc3e0, 0xffffffffffffffff)
	/Users/amansour/go/src/github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp/olrequest.go:229 +0x26f
github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp.setBearerToken(0xc0001092c0, 0xc000108f40, 0x30)
	/Users/amansour/go/src/github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp/olrequest.go:248 +0x40
github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp.(*OLHTTPService).attachHeaders(0xc0001092c0, 0xc0000be800, 0xc000026940, 0x1e, 0x15472f6, 0x6, 0xc000021bc0, 0x14837e0, 0xc000036780, 0x0, ...)
	/Users/amansour/go/src/github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp/olrequest.go:180 +0x3f3
github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp.(*OLHTTPService).executeHTTP(0xc0001092c0, 0xc0000be800, 0xc000026940, 0x1e, 0x15472f6, 0x6, 0xc000021bc0, 0x14837e0, 0xc000036780, 0x0, ...)
	/Users/amansour/go/src/github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp/olrequest.go:198 +0xaf
github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp.OLHTTPService.Read(0x154a66c, 0xf, 0xc000034013, 0x40, 0xc000034077, 0x40, 0xc00002e132, 0x13, 0x15f57c0, 0xc000021ad0, ...)
	/Users/amansour/go/src/github.com/onelogin/onelogin-go-sdk/pkg/services/olhttp/olrequest.go:62 +0x1b1
github.com/onelogin/onelogin-go-sdk/pkg/services/apps.V2Service.Query(0xc000026940, 0x1e, 0x154a4e6, 0xf, 0x15ff9c0, 0xc0000f6100, 0xc000036780, 0x0, 0xd0d2a506, 0xd7e456b3b7246e2a, ...)
	/Users/amansour/go/src/github.com/onelogin/onelogin-go-sdk/pkg/services/apps/v2.go:33 +0x187
github.com/onelogin/onelogin/terraform/importables.OneloginAppsImportable.GetAllApps(0x0, 0x0, 0x15f6180, 0xc000021b00, 0x15f6180, 0xc000021b00, 0x0, 0x0, 0x154791e)
	/Users/amansour/go/src/github.com/onelogin/onelogin/terraform/importables/onelogin_apps.go:55 +0x22a
github.com/onelogin/onelogin/terraform/importables.OneloginAppsImportable.ImportFromRemote(0x0, 0x0, 0x15f6180, 0xc000021b00, 0xc0000100a8, 0x0, 0x0)
	/Users/amansour/go/src/github.com/onelogin/onelogin/terraform/importables/onelogin_apps.go:21 +0xb2
github.com/onelogin/onelogin/terraform/import.ImportTFStateFromRemote(0x15f61c0, 0xc00000e820)
	/Users/amansour/go/src/github.com/onelogin/onelogin/terraform/import/import.go:30 +0x144
github.com/onelogin/onelogin/cmd.terraformImport(0xc00010e000, 0xc00006f380, 0x1, 0x1)
	/Users/amansour/go/src/github.com/onelogin/onelogin/cmd/terraform-import.go:68 +0x9c7
github.com/spf13/cobra.(*Command).execute(0xc00010e000, 0xc00006f340, 0x1, 0x1, 0xc00010e000, 0xc00006f340)
	/Users/amansour/go/src/github.com/spf13/cobra/command.go:833 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1917960, 0x103cd8a, 0x18d9cc0, 0xc000000180)
	/Users/amansour/go/src/github.com/spf13/cobra/command.go:917 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/amansour/go/src/github.com/spf13/cobra/command.go:867
github.com/onelogin/onelogin/cmd.Execute()
	/Users/amansour/go/src/github.com/onelogin/onelogin/cmd/root.go:46 +0x31
main.main()
	/Users/amansour/go/src/github.com/onelogin/onelogin/main.go:23 +0x20
```

Terraform version: 0.12.24
OneLogin terraform provider is installed
This has also been tried on more than one environment to check if the local set up was the problem

**Comment by ghost** [comment]
This has been solved by adding `https://` to the api url. Not sure if I should close the ticket now or keep it till that is fixed

**Comment by dcaponi** [comment]
I'll close it since you're unblocked. I track the underlying causes (like missing `https://`) on an internal kanban board so we'll be addressing this soon (likely in the next release).
